### ISSUE TITLE
DESIGN - Data Pipelining

### ISSUE THREAD

**Issue by winder** [algorand/conduit#11]
## Problem

Conduit's data pipeline currently processes a single round of data at a time which means there is downtime for the exporter every time a new block of data is fetched and processed.

In one test, the overhead was only 1.7ms per round, but over 25 million rounds that adds up to nearly 12 hours.

The overhead for the filter processor is even more overhead. Perhaps much more for a complex filter.

## Solution

Pipeline data processing so that each plugin is always executing the next round. If there are 5 plugins enabled there should be at least 5 rounds in the pipeline so that the slowest plugin is never starved for work.

**Comment by tzaffi** [comment]
## Design Artifact

https://docs.google.com/document/d/1IdgHgIZ4JM-9xJNnx3ya142DFTFKMkoEgl-sTr4Dloc/edit

**Comment by tzaffi** [comment]
## Final Design Artifact V2

https://docs.google.com/document/d/15I_dhYHAgqA6yemd0sq9BZxbRu8IajNoLk8CDwZDTfc/edit?usp=sharing

We follow the approach defined in the [Next Steps section](https://docs.google.com/document/d/15I_dhYHAgqA6yemd0sq9BZxbRu8IajNoLk8CDwZDTfc/edit#bookmark=id.occa82cu1avh) of the doc.
