### ISSUE TITLE
Exiting with error:     pipeline init error: Pipeline.Init(): could not initialize importer (algod): received unexpected error (StatusAfterBlock) waiting for node to catchup: did not reach expected round 37431745 != 37440000.

### ISSUE THREAD

**Issue by imaiops** [algorand/conduit#166]
Log error: 
`Exiting with error: pipeline init error: Pipeline.Init(): could not initialize importer (algod): received unexpected error (StatusAfterBlock) waiting for node to catchup: did not reach expected round 37431745 != 37440000. `
How to fix it ? Thanks

**Comment by gmalouf** [comment]
@imaiops is this still an issue?
