### ISSUE TITLE
go generate ./... && cd cmd/conduit && go build -ldflags='-X 

### ISSUE THREAD

**Issue by block98ct** [algorand/conduit#169]
palash@Palash-pc:~/conduit$ make conduit
make: go: No such file or directory
/bin/sh: 1: go: not found
go generate ./... && cd cmd/conduit && go build -ldflags='-X github.com/algorand/conduit/version.Hash=9364f216b8986b0f96e74dffd57c73b66903e90f -X github.com/algorand/conduit/version.ShortHash=9364f21 -X github.com/algorand/conduit/version.CompileTime=2024-04-26T11:52:28+0000 -X "github.com/algorand/conduit/version.ReleaseVersion=Dev Build"'
/bin/sh: 1: go: not found
/bin/sh: 1: go: not found
make: *** [Makefile:22: conduit] Error 127

**Comment by jasonpaulos** [comment]
Building conduit requires golang version 1.20. You must install that and make sure the `go` command is on your path in order for `make conduit` to work.

Closing because I don't believe this is a problem with our repo. Feel free to respond and I will reopen if necessary
