### ISSUE TITLE
Exiting with error:	pipeline init error: Pipeline.Init(): could not initialize importer (algod): Get "http://127.0.0.1:8080/genesis": dial tcp 127.0.0.1:8080: connect: connection refused.

### ISSUE THREAD

**Issue by block98ct** [algorand/conduit#171]
I am trying to sync an Algorand node with PostgreSQL. For that, I am setting up a conduit, but I am encountering an error.

**Comment by jasonpaulos** [comment]
That message indicates conduit cannot connect to your algod node. Please double check the port number and ensure conduit has the correct auth token for the node. These can be found by looking at the `algod.net` and `algod.token` files inside the node's data directory.

You can double check these are valid with curl, like so:
```bash
ALGOD_TOKEN="<insert your algod token>"
ALGOD_PORT="<insert your algod port>"
curl -H "X-Algo-API-Token:${ALGOD_TOKEN}" "http://127.0.0.1:${ALGOD_PORT}/v2/status"
```

**Comment by jasonpaulos** [comment]
Please feel free to comment and I will reopen if you find an issue with conduit
