### ISSUE TITLE
Not able to parse new blocks with incentive fields

### ISSUE THREAD

**Issue by joe-p** [algorand/conduit#173]
### Subject of the issue

Conduit is not able to parse new blocks with incentive fields

### Your environment

Latest algod and conduit docker images

### Steps to reproduce

1. Attempt to run conduit against latest algod

### Expected behaviour

Conduit is able to process block

### Actual behaviour

`importer algod.GetBlock() error getting block for round 1, check node configuration: error decoding block for round 1: msgpack decode error [pos 13]: no matching struct field found when decoding stream map with key bi`

**Comment by jasonpaulos** [comment]
@joe-p are you running consensus version future when you see this issue?

**Comment by joe-p** [comment]
@jasonpaulos Ah yeah we were using future consensus.

**Comment by joe-p** [comment]
Re-opening this issue because it's happening without vFuture as well
