### ISSUE TITLE
Automate publishing docs to docs repo.

### ISSUE THREAD

**Issue by winder** [algorand/conduit#33]
## Problem

For the release, documentation is being manually published. In the future, we would like to automate the process of copying the Conduit docs directory to the docs repo.

The docs repo has a page order plugin to configure what order subpages show up in the navigation bar, we may need to create some `.pages` files in order to make sure the doc copy is a simple process.

## Solution

Update github actions on https://github.com/algorand/docs to copy documentation over.

**Comment by JasonWeathersby** [comment]
Changes made to get it to work with the docs site:

Added .pages file in root folder of conduit docs
title: Conduit
arrange:
  - GettingStarted.md
  - Configuration.md
  - Development.md


GettingStarted.md
Tutorials section had to change:
[Conduit tutorials](./tutorials). Here are a few of the highlights:

* [How to write block data to the filesystem](./tutorials/WritingBlocksToFile.md)
* [A deep dive into the filter processor](./tutorials/FilterDeepDive.md)
* [The differences and migration paths between Indexer & Conduit](./tutorials/IndexerMigration.md)

Ie a nl after highlights


Link in:WritingBlocksToFile.md need to be changed
First we need to make sure we have Conduit installed. Head over to [GettingStarted.md](../GettingStarted.md)


Link in: home.md in plugins 
Had * [file_reader](file_reader.md)
Had to delete as it did not exist
